apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/mikes429/argocd-odf.git'
    path: acm/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
    syncOptions:
      - Validate=false
