##
# LSO Chart values
##
#

#Nodes that have the label cluster.ocs.openshift.io/openshift-storage='' will
#be used to discover local attach devices for LSO to use
logging:
# LSO version Channel
  channel: 'stable'
  application:
    retention: '7d'
  infra:
    retention: '7d'
  audit:
    retention: '7d'
  elasticsearch:
    replicas: '3'
    storageclass: 'ocs-storagecluster-ceph-rbd' 
    storagesize: '200G'
    limits:
      memory: '16Gi'
    requests:
      memory: '16Gi'
    redundancy: 'SingleRedundancy'
  kibana:
    replicas: '3'
# If OCP Cluster is deployed in AWS and dedicated option enabled it will deploy 3 ODF workers(m5.4xlarge) using machinesets one per AZ, .
dedicated:
  enabled: true
  vsphere:
    #you can use $ oc get machineset -n openshift-machine-api -o jsonpath='{.items[0].metadata.labels.machine\.openshift\.io/cluster-api-cluster}'
    clusterid: 'ocnp2-mwdx5'
    diskGiB: '120'
    memoryMiB: '32768'
    numCPUs: '8'
    networkName: 'DSwitch01-VM Network'
    datacenter: 'Home'
    datastore: 'vsanDatastore'
    folder: '/Home/vm/ocnp2-mwdx5'
    resourcePool: '/Home/host/SDDC/Resources'
    vcenter: '192.168.0.10'
