apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  labels:
    argocd.argoproj.io/managed-by: "openshift-gitops"
  name: "instance" 
  namespace: "openshift-logging"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  managementState: "Managed"  
  logStore:
    type: "elasticsearch"  
    retentionPolicy: 
      application:
        maxAge: '{{ .Values.logging.application.retention }}'
      infra:
        maxAge: '{{ .Values.logging.infra.retention }}'
      audit:
        maxAge: '{{ .Values.logging.audit.retention }}'
    elasticsearch:
      nodeCount: {{ .Values.logging.elasticsearch.replicas }} 
      storage:
        storageClassName: {{ .Values.logging.elasticsearch.storageclass }}  
        size: {{ .Values.logging.elasticsearch.storagesize }}
      resources: 
          limits:
            memory: {{ .Values.logging.elasticsearch.limits.memory }}
          requests:
            memory: {{ .Values.logging.elasticsearch.requests.memory }}
      proxy: 
        resources:
          limits:
            memory: {{ .Values.logging.proxy.limits.memory }}
          requests:
            memory: {{ .Values.logging.proxy.requests.memory }}
      redundancyPolicy: {{ .Values.logging.elasticsearch.redundancy }}
  visualization:
    type: "kibana"  
    kibana:
      replicas: {{ .Values.logging.kibana.replicas }} 
  collection:
    logs:
      type: "fluentd"  
      fluentd: {}
