apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: "openshift-gitops"
    openshift.io/cluster-monitoring: 'true'
  name: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec: {}

