apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: "PostSync"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  imagePullSecret: acm-pullsecret
