apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync  
  name: openshift-advanced-cluster-mgmt
  namespace: open-cluster-management 
spec:
  targetNamespaces:
  - open-cluster-management
