apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  channel: '{{ .Values.quay.channel }}'
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
