kind: Secret
apiVersion: v1
metadata:
  name: init-config-bundle-secret
  namespace: quay-enterprise
  labels:
    app.kubernetes.io/instance: deploy-quay
    argocd.argoproj.io/managed-by: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '0'
data:
  config.yaml: >-
    RkVBVFVSRV9VU0VSX0lOSVRJQUxJWkU6IHRydWUKQlJPV1NFUl9BUElfQ0FMTFNfWEhSX09OTFk6IGZhbHNlClNVUEVSX1VTRVJTOgotIHF1YXlhZG1pbgpGRUFUVVJFX1VTRVJfQ1JFQVRJT046IGZhbHNlCkZFQVRVUkVfUVVPVEFfTUFOQUdFTUVOVDogdHJ1ZQpGRUFUVVJFX0JVSUxEX1NVUFBPUlQ6IHRydWUKRkVBVFVSRV9QUk9YWV9DQUNIRTogdHJ1ZQpERUZBVUxUX1NZU1RFTV9SRUpFQ1RfUVVPVEFfQllURVM6IDEwMjQwMDAwMAo=
type: Opaque
