apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: quay-enterprise
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: '{{ .Values.quay.channel }}'
  installPlanApproval: Automatic
  name: quay-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
