---
# Source: clo-argocd/templates/create-wait-pod.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-pod-elasticsearch-operator-job
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    compare-options: IgnoreExtraneous
spec:
  template:
    spec:
      containers:
      - name: wait-pod
        command:
            - /bin/bash
            - -c
            - |
              set -x
              echo "Checking if the elasticsearch operator has finished it's deployment"
              sleep 15
              for i in 'name=elasticsearch-operator'
              do
                oc wait --for condition=Ready pod  --selector=${i} -n openshift-operators-redhat --timeout=180s
                sleep 5
              done
              echo "Elasticsearch operator has been deployed"
              echo "========================"
        image:  registry.redhat.io/openshift4/ose-cli:v4.10
      serviceAccount: query-pods
      serviceAccountName: query-pods
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
